
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 28 13:42:31 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ComillasD = 10;
  public static final int VAL = 13;
  public static final int Numero = 19;
  public static final int ComentarioN = 18;
  public static final int Palabra = 20;
  public static final int CorcheteC = 9;
  public static final int CorcheteA = 8;
  public static final int Espacioo = 22;
  public static final int ID = 12;
  public static final int Coma = 7;
  public static final int ComentarioB = 17;
  public static final int LlaveC = 4;
  public static final int LlaveA = 3;
  public static final int Negativo = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ComillasS = 11;
  public static final int Real = 15;
  public static final int Espacio = 14;
  public static final int SaltoLinea = 2;
  public static final int Alfanumerico = 16;
  public static final int Error = 21;
  public static final int DosP = 5;
}

